# Generated by Django 5.0.4 on 2024-05-08 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('공학관', '공학관'), ('국제관', '국제관'), ('경영관', '경영관'), ('도서관', '도서관'), ('미래관', '미래관'), ('법학관', '법학관'), ('북악관', '북악관'), ('복지관', '복지관')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('available_time', models.CharField(max_length=100)),
                ('how_to_use', models.CharField(max_length=200)),
                ('specification', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
